---
# tasks file for nginx
  - name: Install Nginx
    apt:
      name=nginx state=present update_cache=yes
    when:
      ansible_os_family == "Debian"
    notify: Nginx Systemd

  - name: Install PHP-CLI
    apt:
      name=php-cli state=present update_cache=yes
    when:
      ansible_os_family == "Debian"
      
  - name: Delete default HTML files
    shell: /bin/rm -rf /usr/share/nginx/html/*.html
    args:
      warn: false

  - name: Replace config file
    vars:
      nginx_user: "{{ remote_server_user }}"
      worker_processes: 2
      worker_connections: 256
    template: 
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0644
    register: result
    failed_when: result.failed == true
    notify: Reload Nginx

  - name: Generate index HTML from template
    template: src=templates/index.html.j2 dest={{ html_dir }}/index.html owner={{ remote_server_user }} mode=0644
    notify: Reload Nginx
